title: My Portfolio
description: Welcome to my GitHub Pages site.
remote_theme: pages-themes/architect@v0.2.0
baseurl: "" # Leave blank unless the site is under a subpath
url:  "https://ziadmotagaly.github.io/"

# Navigation for themes supporting menus
navbar:
  - title: Home
    url: /
  - title: About
    url: /about.html

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one


# Exclude unnecessary files from the site build
exclude:
  - README.md
  - LICENSE




