title: My Portfolio
description: Welcome to my GitHub Pages site.
remote_theme: pages-themes/slate@v0.2.0
baseurl: "" # Leave blank unless the site is under a subpath
url:  "https://ziadmotagaly.github.io/"

# Navigation for themes supporting menus
navbar:
  - title: Home
    url: /
  - title: About
    url: /about.html

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

github_username: https://github.com/ZiadMotagaly

# Exclude unnecessary files from the site build
exclude:
  - README.md
  - LICENSE




